#!/bin/sh

case $BLOCK_BUTTON in
	1) pavucontrol ;;
	3) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
esac

#[ "$(pulsemixer --get-mute)" = "1" ] && printf "" && exit
if [ "$(pulsemixer --get-mute)" = "1" ]; then
    printf ":\n"
    exit
fi

vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "79" ]; then
	icon=""
elif [ "$vol" -gt "49" ]; then
	icon=""
elif [ "$vol" -gt "29" ]; then
	icon=""
else
	icon=""
fi

printf "%s: %s%%\\n" "$icon" "$vol"
