#!/bin/bash

time=${1-30}
region=${2:-nl} # Default region to NL

# Latitude and Longitude (default - Eindhoven)
lat=${3:-51.4393}
lon=${4:-5.47863}

response=$(curl -s "https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=$lat&lon=$lon&region=$region&unit=mm/u")

temp=$(echo "$response" | jq -r .temp) # Temperature

precipitation_data() {
    mapfile -t whole < <(jq -r .precip[] <<< "$response") # All precipitation data in array whole
}

print_precipitation() {
    precipitation_data

    for each in "${whole[@]}"
        do
            echo "$each"
        done
}

precipitation_info1() {
    indice=$(($1 / 5)) # buienalarm sends precipitation data every 5min

    jq -r --argjson indice "$indice" \
        '.precip[:$indice] |
         max |
         if . > 2.5 then
             "殺: Heavy"
         elif . > 1 then
             "殺: Moderate"
         elif . > 0.25 then
             "殺: Light"
         elif . > 0.15 then
             "殺: Drizzle"
         else
             "\nNo rain\n"
         end' <<< "$response"
}

precipitation=$(precipitation_info1 "$time")

echo ": $temp°C $precipitation"
