#!/bin/bash

time=${1-30}
region=${2:-nl} # Default region to NL

# Latitude and Longitude (default - Eindhoven)
lat=${3:-51.4393}
lon=${4:-5.47863}


response=$(curl -s "https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=$lat&lon=$lon&region=$region&unit=mm/u")


temp=$(echo "$response" | jq -r .temp) # Temperature

precipitation_data() {
    mapfile -t whole < <(jq -r .precip[] <<< "$response") # All precipitation data in array whole
}

print_precipitation() {
    precipitation_data

    for each in "${whole[@]}"
        do
            echo "$each"
        done
}

precipitation_info1() {
    indice=$(($1 / 5)) # buienalarm sends precipitation data every 5min

    jq -r --argjson indice "$indice" \
        '.precip[:$indice] |
         max |
         if . > 2.5 then
             ": Heavy"
         elif . > 1 then
             ": Moderate"
         elif . > 0.25 then
             ": Light"
         elif . > 0.15 then
             ": Drizzle"
         else
             empty
         end' <<< "$response"
}

precipitation=$(precipitation_info1 "$time")

rain_type_lat=$( awk -v n=$lat 'BEGIN{printf("%.f\n", n*100)}')
rain_type_lon=$( awk -v n=$lon 'BEGIN{printf("%.f\n", n*100)}')
rain_type=$(curl "https://api.meteoplaza.com/v2/meteo/completelocation/$rain_type_lat.$rain_type_lon?lang=en" | jq -r .MeteoWarning.Title)

if [ "$precipitation" ]; then
    echo ": $temp°C | $precipitation | Type: $rain_type"
else
    echo ": $temp°C"
fi
